# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  vlang_config = debug
endif
ifeq ($(config),release)
  vlang_config = release
endif

PROJECTS := vlang

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

vlang:
ifneq (,$(vlang_config))
	@echo "==== Building vlang ($(vlang_config)) ===="
	@${MAKE} --no-print-directory -C . -f vlang.make config=$(vlang_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f vlang.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   vlang"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"